grpc:
  port: 8082

logging:
  path: logs
  level: INFO
  level.org.hibernate: INFO
  level.com.github.windmill312: DEBUG

spring:
  application:
    name: product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_products
    username: a.sychev
    password: "Ujkjcjdfzgjxnf8"


  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false